In [2]:
import numpy as np
import pandas as pd

df = pd.read_csv("学生成绩.csv",encoding="GBK")

### 查看内容

In [5]:
df

           学号    姓名    班级 性别  出生年份   籍贯  数学   语文   英语
0   166241101   童绮琴  信管19  男  2001   天津  99   71   65
1   166241102   酆友容  信管20  女  2002   广西  81   64   52
2   166241103  端木孤菱  信管21  男  2002   湖南  67   90   98
3   166241104   闳芳苓  信管22  女  2002   湖北  89  100   90
4   166241105   温靖易  信管23  女  2002   吉林  80   70   77
5   166241106   祖海亦  信管24  女  2002   天津  72   91   65
6   166241107   考依玉  信管25  男  2002   西藏  73   83   66
7   166241108   娄昊英  信管26  女  2001   湖南  84   85   59
8   166241109   剧星星  信管27  男  2002   北京  66   87   64
9   166241110  呼延寻桃  信管28  女  2001   海南  78   65   92
10  166241111   天忻然  信管29  女  2001   海南  89   50   98
11  166241112   校惜文  信管30  女  2002   吉林  77   64   56
12  166241113   汲慧颖  信管31  女  2001   云南  73   85   76
13  166241114  东郭勇捷  信管32  男  2001   安徽  85   59   73
14  166241115   声恨之  信管33  女  2002   重庆  41   60   60
15  166241116   皮谷之  信管34  女  2001  黑龙江  68   68   93
16  166241117   翠夜玉  信管35  男  2002   北京  92   64   85
17  166241118   岳秀婉  信管36  男  2001   安徽  75   84   71
18  166241119   侍语雪  信管37  男  2001   四川  81   90   97
19  166241120   多思菱  信管38  男  2001   福建  84   81   55
20  166241121   何笑天  信管39  男  2002   河北  68   86   53
21  166241122   裴冬卉  信管40  女  2002   安徽  82   81   54
22  166241123   脱迎波  信管41  男  2002   山西  82   82   64
23  166241124  诸葛弘雅  信管42  女  2002   江苏  68   91   70
24  166241125  澹台高丽  信管43  男  2001   贵州  83   84   63
25  166241126   甄心诺  信管44  女  2001   江西  89   58   88
26  166241127   明静安  信管45  女  2002   重庆  83   67  100
27  166241128   祝文漪  信管46  女  2001   新疆  73   88   92
28  166241129   江天薇  信管47  女  2001   江西  75   93   63
29  166241130   劳博学  信管48  男  2002   天津  54   66   74
30  166241201   析梦菡  电商19  男  2001   浙江  80   60   71
31  166241202   夕项明  电商20  男  2001   天津  68   95  100
32  166241203   镜梦桃  电商21  男  2001   西藏  74   56   66
33  166241204   风凝雁  电商22  男  2001   广东  94   79   81
34  166241205   毓雨梅  电商23  女  2001   北京  70   65   70
35  166241206   卞锐翰  电商24  男  2002   江苏  79   85   80
36  166241207   亓佩兰  电商25  男  2002  内蒙古  91   62   89
37  166241208   疏春燕  电商26  女  2001   台湾  55   83   70
38  166241209   亥恺乐  电商27  女  2001   湖北  66   64   95
39  166241210   丘绿柳  电商28  女  2002   广西  73   91   50
40  166241211   隐清懿  电商29  女  2001   四川  70   72   68
41  166241212   查琴韵  电商30  男  2002   福建  73   89   55
42  166241213   翦清芬  电商31  女  2002   宁夏  64   97   56
43  166241214   普依白  电商32  女  2002   北京  63   52   72
44  166241215   淦恨荷  电商33  男  2002   北京  63   97   54
45  166241217   刑皎洁  电商34  男  2001   上海  83   96   83
46  166241218   淡振华  电商35  男  2002   山东  84   63   97
47  166241219   城恨寒  电商36  男  2001   四川  81   70   54
48  166241220   晁柔绚  电商37  男  2002   甘肃  74   68   82
49  166241221   幸晴岚  电商38  男  2001  内蒙古  70   89   97
50  166241222   俞骊艳  电商39  女  2001   吉林  69   59   79
51  166241223   解阳文  电商40  女  2002   云南  72   85   86
52  166241224   戈含之  电商41  男  2001   西藏  64   56   64
53  166241225   郑月华  电商42  男  2002   北京  95   56   96
54  166241226   乾冬卉  电商43  女  2001   甘肃  91   60   62
55  166241227   甫念真  电商44  男  2002   广东  88   66   65
56  166241228   潘淑婉  电商45  男  2002   福建  79   81   98

### 查看前n行内容

In [3]:
df.head()

          学号    姓名    班级 性别  出生年份  籍贯  数学   语文  英语
0  166241101   童绮琴  信管19  男  2001  天津  99   71  65
1  166241102   酆友容  信管20  女  2002  广西  81   64  52
2  166241103  端木孤菱  信管21  男  2002  湖南  67   90  98
3  166241104   闳芳苓  信管22  女  2002  湖北  89  100  90
4  166241105   温靖易  信管23  女  2002  吉林  80   70  77

### 查看末尾n行内容

In [4]:
df.tail()

           学号   姓名    班级 性别  出生年份  籍贯  数学  语文  英语
52  166241224  戈含之  电商41  男  2001  西藏  64  56  64
53  166241225  郑月华  电商42  男  2002  北京  95  56  96
54  166241226  乾冬卉  电商43  女  2001  甘肃  91  60  62
55  166241227  甫念真  电商44  男  2002  广东  88  66  65
56  166241228  潘淑婉  电商45  男  2002  福建  79  81  98

In [6]:
df.columns

Index(['学号', '姓名', '班级', '性别', '出生年份', '籍贯', '数学', '语文', '英语'], dtype='object')

In [11]:
len(df)

57

In [12]:
df.index

RangeIndex(start=0, stop=57, step=1)

In [14]:
df.dtypes

学号       int64
姓名      object
班级      object
性别      object
出生年份     int64
籍贯      object
数学       int64
语文       int64
英语       int64
dtype: object